// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pdfengine$0 from "../pdfengine/models.js";

export class OpenedDocument {
    "kind": string;
    "name": string;
    "text"?: string;
    "pdf": PDFDocument;

    /** Creates a new OpenedDocument instance. */
    constructor($$source: Partial<OpenedDocument> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("pdf" in $$source)) {
            this["pdf"] = (new PDFDocument());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpenedDocument instance from a string or object.
     */
    static createFrom($$source: any = {}): OpenedDocument {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pdf" in $$parsedSource) {
            $$parsedSource["pdf"] = $$createField3_0($$parsedSource["pdf"]);
        }
        return new OpenedDocument($$parsedSource as Partial<OpenedDocument>);
    }
}

export const PDFCreateRequest = pdfengine$0.ComposeRequest;
export type PDFCreateRequest = pdfengine$0.ComposeRequest;

export const PDFDocument = pdfengine$0.Document;
export type PDFDocument = pdfengine$0.Document;

export const PDFResult = pdfengine$0.Result;
export type PDFResult = pdfengine$0.Result;

// Private type creation functions
const $$createType0 = pdfengine$0.Document.createFrom;
