// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class LocalModelInfo {
    "name": string;
    "path": string;
    "sizeBytes": number;
    "modTime": string;

    /** Creates a new LocalModelInfo instance. */
    constructor($$source: Partial<LocalModelInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("sizeBytes" in $$source)) {
            this["sizeBytes"] = 0;
        }
        if (!("modTime" in $$source)) {
            this["modTime"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalModelInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalModelInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalModelInfo($$parsedSource as Partial<LocalModelInfo>);
    }
}
