// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Capabilities describes the backend compiled for the current platform.
 */
export class Capabilities {
    "available": boolean;
    "backend": string;
    "minimumVersion": string;
    "engines"?: string[];

    /** Creates a new Capabilities instance. */
    constructor($$source: Partial<Capabilities> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("backend" in $$source)) {
            this["backend"] = "";
        }
        if (!("minimumVersion" in $$source)) {
            this["minimumVersion"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Capabilities instance from a string or object.
     */
    static createFrom($$source: any = {}): Capabilities {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("engines" in $$parsedSource) {
            $$parsedSource["engines"] = $$createField3_0($$parsedSource["engines"]);
        }
        return new Capabilities($$parsedSource as Partial<Capabilities>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
