// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as file$0 from "../file/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as litertlm$0 from "../litertlm/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as llm$0 from "../llm/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pdfengine$0 from "../pdfengine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as translation$0 from "../translation/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelTranslation aborts the active translation request, if any.
 */
export function CancelTranslation(): $CancellablePromise<void> {
    return $Call.ByID(3232651519);
}

export function ConfirmClearSource(): $CancellablePromise<boolean> {
    return $Call.ByID(2743851642);
}

export function CreateTranslatedPDF(req: file$0.PDFCreateRequest): $CancellablePromise<file$0.PDFResult> {
    return $Call.ByID(4170096138, req).then(($result: any) => {
        return $$createType0($result);
    });
}

export function DownloadLiteRTModel(repoOrURL: string, token: string): $CancellablePromise<string> {
    return $Call.ByID(1915904537, repoOrURL, token);
}

export function GetHostProviderSettings(): $CancellablePromise<llm$0.ProviderSettings> {
    return $Call.ByID(4293725932).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetLiteRTModelsDir(): $CancellablePromise<string> {
    return $Call.ByID(1520442641);
}

/**
 * GetModels returns the list of models from the configured provider endpoint.
 */
export function GetModels(settings: llm$0.ProviderSettings): $CancellablePromise<llm$0.ModelInfo[]> {
    return $Call.ByID(194005692, settings).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetPlatformCapabilities(): $CancellablePromise<translation$0.Capabilities> {
    return $Call.ByID(1948844707).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetWebServerSettings(): $CancellablePromise<$models.WebServerSettings> {
    return $Call.ByID(2873616034).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetWindowMode(): $CancellablePromise<string> {
    return $Call.ByID(3464172525);
}

export function ListLocalLiteRTModels(): $CancellablePromise<litertlm$0.LocalModelInfo[]> {
    return $Call.ByID(4150302337).then(($result: any) => {
        return $$createType7($result);
    });
}

export function OpenCertificateFolder(): $CancellablePromise<void> {
    return $Call.ByID(3732568537);
}

export function OpenDebugStudioWindow(): $CancellablePromise<void> {
    return $Call.ByID(1954322119);
}

export function OpenDocument(): $CancellablePromise<file$0.OpenedDocument> {
    return $Call.ByID(3147136995).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * OpenFile opens a text file and returns its content
 */
export function OpenFile(): $CancellablePromise<string> {
    return $Call.ByID(3710460632);
}

export function OpenPDF(): $CancellablePromise<file$0.PDFDocument> {
    return $Call.ByID(2331218116).then(($result: any) => {
        return $$createType9($result);
    });
}

export function ReadDebugStudioState(): $CancellablePromise<string> {
    return $Call.ByID(3236427664);
}

export function RecoverPDFCheckpoint(): $CancellablePromise<$models.PDFCheckpointRecovery> {
    return $Call.ByID(2921514870).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * SaveFile saves text to a file
 */
export function SaveFile(content: string): $CancellablePromise<string> {
    return $Call.ByID(3141322869, content);
}

export function SaveHostProviderSettings(settings: llm$0.ProviderSettings): $CancellablePromise<void> {
    return $Call.ByID(2232040833, settings);
}

export function SavePDF(dataBase64: string, defaultFilename: string): $CancellablePromise<string> {
    return $Call.ByID(1657358923, dataBase64, defaultFilename);
}

export function SaveWebServerSettings(input: $models.WebServerSettingsInput): $CancellablePromise<$models.WebServerSettings> {
    return $Call.ByID(3651595085, input).then(($result: any) => {
        return $$createType5($result);
    });
}

export function SelectLiteRTLMModel(): $CancellablePromise<string> {
    return $Call.ByID(3861202836);
}

/**
 * Translate performs the translation via the configured provider.
 */
export function Translate(req: llm$0.TranslationRequest): $CancellablePromise<void> {
    return $Call.ByID(2468393804, req);
}

export function WriteDebugStudioState(state: string): $CancellablePromise<void> {
    return $Call.ByID(3005692031, state);
}

// Private type creation functions
const $$createType0 = pdfengine$0.Result.createFrom;
const $$createType1 = llm$0.ProviderSettings.createFrom;
const $$createType2 = llm$0.ModelInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = translation$0.Capabilities.createFrom;
const $$createType5 = $models.WebServerSettings.createFrom;
const $$createType6 = litertlm$0.LocalModelInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = file$0.OpenedDocument.createFrom;
const $$createType9 = pdfengine$0.Document.createFrom;
const $$createType10 = $models.PDFCheckpointRecovery.createFrom;
