// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as file$0 from "../file/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pdfengine$0 from "../pdfengine/models.js";

export class PDFCheckpointRecovery {
    "found": boolean;
    "document": file$0.PDFDocument;
    "result": file$0.PDFResult;
    "completedPages": number;
    "totalPages": number;
    "status": string;
    "error"?: string;

    /** Creates a new PDFCheckpointRecovery instance. */
    constructor($$source: Partial<PDFCheckpointRecovery> = {}) {
        if (!("found" in $$source)) {
            this["found"] = false;
        }
        if (!("document" in $$source)) {
            this["document"] = (new file$0.PDFDocument());
        }
        if (!("result" in $$source)) {
            this["result"] = (new file$0.PDFResult());
        }
        if (!("completedPages" in $$source)) {
            this["completedPages"] = 0;
        }
        if (!("totalPages" in $$source)) {
            this["totalPages"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PDFCheckpointRecovery instance from a string or object.
     */
    static createFrom($$source: any = {}): PDFCheckpointRecovery {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("document" in $$parsedSource) {
            $$parsedSource["document"] = $$createField1_0($$parsedSource["document"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField2_0($$parsedSource["result"]);
        }
        return new PDFCheckpointRecovery($$parsedSource as Partial<PDFCheckpointRecovery>);
    }
}

export class WebServerSettings {
    "enabled": boolean;
    "port": string;
    "useTls": boolean;
    "certDomain"?: string;
    "certPath"?: string;
    "keyPath"?: string;
    "certificateDirectory": string;
    "configDirectory": string;
    "hasPassword": boolean;
    "url"?: string;

    /** Creates a new WebServerSettings instance. */
    constructor($$source: Partial<WebServerSettings> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("port" in $$source)) {
            this["port"] = "";
        }
        if (!("useTls" in $$source)) {
            this["useTls"] = false;
        }
        if (!("certificateDirectory" in $$source)) {
            this["certificateDirectory"] = "";
        }
        if (!("configDirectory" in $$source)) {
            this["configDirectory"] = "";
        }
        if (!("hasPassword" in $$source)) {
            this["hasPassword"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebServerSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): WebServerSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WebServerSettings($$parsedSource as Partial<WebServerSettings>);
    }
}

export class WebServerSettingsInput {
    "enabled": boolean;
    "port": string;
    "password"?: string;
    "useTls": boolean;
    "certDomain"?: string;
    "certPath"?: string;
    "keyPath"?: string;

    /** Creates a new WebServerSettingsInput instance. */
    constructor($$source: Partial<WebServerSettingsInput> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("port" in $$source)) {
            this["port"] = "";
        }
        if (!("useTls" in $$source)) {
            this["useTls"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebServerSettingsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): WebServerSettingsInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WebServerSettingsInput($$parsedSource as Partial<WebServerSettingsInput>);
    }
}

// Private type creation functions
const $$createType0 = pdfengine$0.Document.createFrom;
const $$createType1 = pdfengine$0.Result.createFrom;
