// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ModelInfo {
    "id": string;
    "displayName"?: string;
    "supportsReasoning": boolean;
    "reasoningOptions"?: string[];

    /** Creates a new ModelInfo instance. */
    constructor($$source: Partial<ModelInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("supportsReasoning" in $$source)) {
            this["supportsReasoning"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ModelInfo {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reasoningOptions" in $$parsedSource) {
            $$parsedSource["reasoningOptions"] = $$createField3_0($$parsedSource["reasoningOptions"]);
        }
        return new ModelInfo($$parsedSource as Partial<ModelInfo>);
    }
}

export class ProviderSettings {
    "mode": string;
    "endpoint": string;
    "apiKey": string;
    "model": string;
    "reasoning"?: string;
    "temperature"?: number;
    "forceShowTemperature": boolean;
    "forceShowReasoning": boolean;
    "enablePostEdit": boolean;
    "enableTopicAwarePostEdit": boolean;
    "enableEnhancedContextTranslation": boolean;
    "enhancedContextGlossary"?: string;
    "enableSmartChunking": boolean;
    "smartChunkSize"?: number;
    "debugTranslationPromptTemplate"?: string;
    "debugPostEditPromptTemplate"?: string;

    /** Creates a new ProviderSettings instance. */
    constructor($$source: Partial<ProviderSettings> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("endpoint" in $$source)) {
            this["endpoint"] = "";
        }
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("forceShowTemperature" in $$source)) {
            this["forceShowTemperature"] = false;
        }
        if (!("forceShowReasoning" in $$source)) {
            this["forceShowReasoning"] = false;
        }
        if (!("enablePostEdit" in $$source)) {
            this["enablePostEdit"] = false;
        }
        if (!("enableTopicAwarePostEdit" in $$source)) {
            this["enableTopicAwarePostEdit"] = false;
        }
        if (!("enableEnhancedContextTranslation" in $$source)) {
            this["enableEnhancedContextTranslation"] = false;
        }
        if (!("enableSmartChunking" in $$source)) {
            this["enableSmartChunking"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderSettings($$parsedSource as Partial<ProviderSettings>);
    }
}

export class TranslationRequest {
    "settings": ProviderSettings;
    "sourceText": string;
    "sourceLang": string;
    "targetLang": string;
    "instruction": string;
    "documentType"?: string;

    /** Creates a new TranslationRequest instance. */
    constructor($$source: Partial<TranslationRequest> = {}) {
        if (!("settings" in $$source)) {
            this["settings"] = (new ProviderSettings());
        }
        if (!("sourceText" in $$source)) {
            this["sourceText"] = "";
        }
        if (!("sourceLang" in $$source)) {
            this["sourceLang"] = "";
        }
        if (!("targetLang" in $$source)) {
            this["targetLang"] = "";
        }
        if (!("instruction" in $$source)) {
            this["instruction"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TranslationRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): TranslationRequest {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField0_0($$parsedSource["settings"]);
        }
        return new TranslationRequest($$parsedSource as Partial<TranslationRequest>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ProviderSettings.createFrom;
