// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTranslation() {
  return window['go']['app']['App']['CancelTranslation']();
}

export function ConfirmClearSource() {
  return window['go']['app']['App']['ConfirmClearSource']();
}

export function CreateTranslatedPDF(arg1) {
  return window['go']['app']['App']['CreateTranslatedPDF'](arg1);
}

export function GetHostProviderSettings() {
  return window['go']['app']['App']['GetHostProviderSettings']();
}

export function GetModels(arg1) {
  return window['go']['app']['App']['GetModels'](arg1);
}

export function GetWebServerSettings() {
  return window['go']['app']['App']['GetWebServerSettings']();
}

export function GetWindowMode() {
  return window['go']['app']['App']['GetWindowMode']();
}

export function OpenCertificateFolder() {
  return window['go']['app']['App']['OpenCertificateFolder']();
}

export function OpenDebugStudioWindow() {
  return window['go']['app']['App']['OpenDebugStudioWindow']();
}

export function OpenFile() {
  return window['go']['app']['App']['OpenFile']();
}

export function OpenPDF() {
  return window['go']['app']['App']['OpenPDF']();
}

export function ReadDebugStudioState() {
  return window['go']['app']['App']['ReadDebugStudioState']();
}

export function RecoverPDFCheckpoint() {
  return window['go']['app']['App']['RecoverPDFCheckpoint']();
}

export function SaveFile(arg1) {
  return window['go']['app']['App']['SaveFile'](arg1);
}

export function SaveHostProviderSettings(arg1) {
  return window['go']['app']['App']['SaveHostProviderSettings'](arg1);
}

export function SavePDF(arg1, arg2) {
  return window['go']['app']['App']['SavePDF'](arg1, arg2);
}

export function SaveWebServerSettings(arg1) {
  return window['go']['app']['App']['SaveWebServerSettings'](arg1);
}

export function Translate(arg1) {
  return window['go']['app']['App']['Translate'](arg1);
}

export function WriteDebugStudioState(arg1) {
  return window['go']['app']['App']['WriteDebugStudioState'](arg1);
}
