// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {llm} from '../models';
import {app} from '../models';

export function CancelTranslation():Promise<void>;

export function ConfirmClearSource():Promise<boolean>;

export function GetHostProviderSettings():Promise<llm.ProviderSettings>;

export function GetModels(arg1:llm.ProviderSettings):Promise<Array<llm.ModelInfo>>;

export function GetWebServerSettings():Promise<app.WebServerSettings>;

export function GetWindowMode():Promise<string>;

export function OpenCertificateFolder():Promise<void>;

export function OpenDebugStudioWindow():Promise<void>;

export function OpenFile():Promise<string>;

export function ReadDebugStudioState():Promise<string>;

export function SaveFile(arg1:string):Promise<string>;

export function SaveHostProviderSettings(arg1:llm.ProviderSettings):Promise<void>;

export function SaveWebServerSettings(arg1:app.WebServerSettingsInput):Promise<app.WebServerSettings>;

export function Translate(arg1:llm.TranslationRequest):Promise<void>;

export function WriteDebugStudioState(arg1:string):Promise<void>;
