// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ComposeRequest {
    "sourceName": string;
    "sourceDataBase64": string;
    "pages": Page[];
    "translatedText": string;

    /** Creates a new ComposeRequest instance. */
    constructor($$source: Partial<ComposeRequest> = {}) {
        if (!("sourceName" in $$source)) {
            this["sourceName"] = "";
        }
        if (!("sourceDataBase64" in $$source)) {
            this["sourceDataBase64"] = "";
        }
        if (!("pages" in $$source)) {
            this["pages"] = [];
        }
        if (!("translatedText" in $$source)) {
            this["translatedText"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ComposeRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ComposeRequest {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pages" in $$parsedSource) {
            $$parsedSource["pages"] = $$createField2_0($$parsedSource["pages"]);
        }
        return new ComposeRequest($$parsedSource as Partial<ComposeRequest>);
    }
}

export class Document {
    "name": string;
    "dataBase64": string;
    "pageCount": number;
    "pages": Page[];
    "sourceText": string;
    "extractedLength": number;

    /** Creates a new Document instance. */
    constructor($$source: Partial<Document> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("dataBase64" in $$source)) {
            this["dataBase64"] = "";
        }
        if (!("pageCount" in $$source)) {
            this["pageCount"] = 0;
        }
        if (!("pages" in $$source)) {
            this["pages"] = [];
        }
        if (!("sourceText" in $$source)) {
            this["sourceText"] = "";
        }
        if (!("extractedLength" in $$source)) {
            this["extractedLength"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Document instance from a string or object.
     */
    static createFrom($$source: any = {}): Document {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pages" in $$parsedSource) {
            $$parsedSource["pages"] = $$createField3_0($$parsedSource["pages"]);
        }
        return new Document($$parsedSource as Partial<Document>);
    }
}

export class Page {
    "pageNumber": number;
    "width": number;
    "height": number;
    "text": string;
    "blocks": TextBlock[];

    /** Creates a new Page instance. */
    constructor($$source: Partial<Page> = {}) {
        if (!("pageNumber" in $$source)) {
            this["pageNumber"] = 0;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("blocks" in $$source)) {
            this["blocks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Page instance from a string or object.
     */
    static createFrom($$source: any = {}): Page {
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("blocks" in $$parsedSource) {
            $$parsedSource["blocks"] = $$createField4_0($$parsedSource["blocks"]);
        }
        return new Page($$parsedSource as Partial<Page>);
    }
}

export class Result {
    "name": string;
    "dataBase64": string;
    "pageCount": number;
    "warning"?: string;

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("dataBase64" in $$source)) {
            this["dataBase64"] = "";
        }
        if (!("pageCount" in $$source)) {
            this["pageCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Result($$parsedSource as Partial<Result>);
    }
}

export class TextBlock {
    "id": string;
    "pageNumber": number;
    "blockIndex": number;
    "x": number;
    "y": number;
    "width": number;
    "height": number;
    "fontSize": number;
    "role": string;
    "text": string;
    "regions"?: TextRegion[];

    /** Creates a new TextBlock instance. */
    constructor($$source: Partial<TextBlock> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("pageNumber" in $$source)) {
            this["pageNumber"] = 0;
        }
        if (!("blockIndex" in $$source)) {
            this["blockIndex"] = 0;
        }
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("fontSize" in $$source)) {
            this["fontSize"] = 0;
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TextBlock instance from a string or object.
     */
    static createFrom($$source: any = {}): TextBlock {
        const $$createField10_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("regions" in $$parsedSource) {
            $$parsedSource["regions"] = $$createField10_0($$parsedSource["regions"]);
        }
        return new TextBlock($$parsedSource as Partial<TextBlock>);
    }
}

export class TextRegion {
    "x": number;
    "y": number;
    "width": number;
    "height": number;

    /** Creates a new TextRegion instance. */
    constructor($$source: Partial<TextRegion> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TextRegion instance from a string or object.
     */
    static createFrom($$source: any = {}): TextRegion {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TextRegion($$parsedSource as Partial<TextRegion>);
    }
}

// Private type creation functions
const $$createType0 = Page.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = TextBlock.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = TextRegion.createFrom;
const $$createType5 = $Create.Array($$createType4);
